In [9]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt  
from sklearn import linear_model

In [10]:
df=pd.read_csv('../Linear_Regression/homeprice.csv')
df


town  area   price
0   monroe township  2600  550000
1   monroe township  3000  565000
2   monroe township  3200  610000
3   monroe township  3600  680000
4   monroe township  4000  725000
5      west windsor  2600  585000
6      west windsor  2800  615000
7      west windsor  3300  650000
8      west windsor  3600  710000
9       robinsville  2600  575000
10      robinsville  2900  600000
11      robinsville  3100  620000
12      robinsville  3600  695000

In [20]:

rooms =pd.array([2,5,3,6,3,8,2,7,2,8,4,3,2])
df['rooms']=p


town  area   price  rooms
0   monroe township  2600  550000      2
1   monroe township  3000  565000      5
2   monroe township  3200  610000      3
3   monroe township  3600  680000      6
4   monroe township  4000  725000      3
5      west windsor  2600  585000      8
6      west windsor  2800  615000      2
7      west windsor  3300  650000      7
8      west windsor  3600  710000      2
9       robinsville  2600  575000      8
10      robinsville  2900  600000      4
11      robinsville  3100  620000      3
12      robinsville  3600  695000      2

In [21]:
age = pd.array([1,4,7,6,12,90,9,4,20,15,8,1,10])
df['age']=age
df

town  area   price  rooms  age
0   monroe township  2600  550000      2    1
1   monroe township  3000  565000      5    4
2   monroe township  3200  610000      3    7
3   monroe township  3600  680000      6    6
4   monroe township  4000  725000      3   12
5      west windsor  2600  585000      8   90
6      west windsor  2800  615000      2    9
7      west windsor  3300  650000      7    4
8      west windsor  3600  710000      2   20
9       robinsville  2600  575000      8   15
10      robinsville  2900  600000      4    8
11      robinsville  3100  620000      3    1
12      robinsville  3600  695000      2   10

In [26]:
reg = linear_model.LinearRegression()
reg.fit(df[['area','age','rooms']],df.price)


LinearRegression()

In [28]:
reg.coef_

array([  122.2446206,   481.6069385, -1878.9063584])

In [29]:
reg.intercept_

245651.87458107725

In [31]:
reg.predict([[2600,1,2]])

array([560211.68237032])

In [32]:
reg.predict([[3600,10,2]])

array([686790.7654197])