In [1]:
import pandas as pd 
import numpy as np 


In [2]:
df=pd.read_csv('../Linear_Regression/homeprice.csv')
df.head(5)

town  area   price
0  monroe township  2600  550000
1  monroe township  3000  565000
2  monroe township  3200  610000
3  monroe township  3600  680000
4  monroe township  4000  725000

In [3]:
dummies =pd.get_dummies(df.town)
dummies.head(5)

monroe township  robinsville  west windsor
0                1            0             0
1                1            0             0
2                1            0             0
3                1            0             0
4                1            0             0

In [4]:
merge =pd.concat([df,dummies],axis='columns')
merge.head(5)

town  area   price  monroe township  robinsville  west windsor
0  monroe township  2600  550000                1            0             0
1  monroe township  3000  565000                1            0             0
2  monroe township  3200  610000                1            0             0
3  monroe township  3600  680000                1            0             0
4  monroe township  4000  725000                1            0             0

In [6]:
final =merge.drop(['town','west windsor'],axis='columns')
final.head(5)

area   price  monroe township  robinsville
0  2600  550000                1            0
1  3000  565000                1            0
2  3200  610000                1            0
3  3600  680000                1            0
4  4000  725000                1            0

In [7]:
from sklearn.linear_model import LinearRegression
model =LinearRegression()

In [9]:
X= final.drop('price',axis='columns')
X.head(5)

area  monroe township  robinsville
0  2600                1            0
1  3000                1            0
2  3200                1            0
3  3600                1            0
4  4000                1            0

In [10]:
y =final.price
y.head(5)

0    550000
1    565000
2    610000
3    680000
4    725000
Name: price, dtype: int64

In [11]:
model.fit(X,y)

LinearRegression()

In [12]:
model.predict([[2800,0,1]])

array([590775.63964739])

In [13]:
model.predict([[3400,0,0]])

array([681241.66845839])

In [14]:
model.predict([[3600,1,0]])

array([666607.18125134])

In [17]:
model.score(X,y)

0.9573929037221873

In [ ]:
df

In [18]:
from sklearn.preprocessing import LabelEncoder
le= LabelEncoder()

In [19]:
dfle=df

In [20]:
dfle.town=le.fit_transform(dfle.town)
dfle

town  area   price
0      0  2600  550000
1      0  3000  565000
2      0  3200  610000
3      0  3600  680000
4      0  4000  725000
5      2  2600  585000
6      2  2800  615000
7      2  3300  650000
8      2  3600  710000
9      1  2600  575000
10     1  2900  600000
11     1  3100  620000
12     1  3600  695000

In [22]:
X=dfle[['town','area']].values
X

array([[   0, 2600],
       [   0, 3000],
       [   0, 3200],
       [   0, 3600],
       [   0, 4000],
       [   2, 2600],
       [   2, 2800],
       [   2, 3300],
       [   2, 3600],
       [   1, 2600],
       [   1, 2900],
       [   1, 3100],
       [   1, 3600]], dtype=int64)

In [24]:
y=dfle.price
y

0     550000
1     565000
2     610000
3     680000
4     725000
5     585000
6     615000
7     650000
8     710000
9     575000
10    600000
11    620000
12    695000
Name: price, dtype: int64

In [ ]:
#Below Code need to get  onhodencoder from sklearn

In [28]:
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer([("town", OneHotEncoder(), [0])], remainder = 'passthrough')

In [29]:
X= ct.fit_transform(X)
X

array([[1.0e+00, 0.0e+00, 0.0e+00, 2.6e+03],
       [1.0e+00, 0.0e+00, 0.0e+00, 3.0e+03],
       [1.0e+00, 0.0e+00, 0.0e+00, 3.2e+03],
       [1.0e+00, 0.0e+00, 0.0e+00, 3.6e+03],
       [1.0e+00, 0.0e+00, 0.0e+00, 4.0e+03],
       [0.0e+00, 0.0e+00, 1.0e+00, 2.6e+03],
       [0.0e+00, 0.0e+00, 1.0e+00, 2.8e+03],
       [0.0e+00, 0.0e+00, 1.0e+00, 3.3e+03],
       [0.0e+00, 0.0e+00, 1.0e+00, 3.6e+03],
       [0.0e+00, 1.0e+00, 0.0e+00, 2.6e+03],
       [0.0e+00, 1.0e+00, 0.0e+00, 2.9e+03],
       [0.0e+00, 1.0e+00, 0.0e+00, 3.1e+03],
       [0.0e+00, 1.0e+00, 0.0e+00, 3.6e+03]])

In [30]:
X=X[:,1:] # remove zeroth columns
X

array([[0.0e+00, 0.0e+00, 2.6e+03],
       [0.0e+00, 0.0e+00, 3.0e+03],
       [0.0e+00, 0.0e+00, 3.2e+03],
       [0.0e+00, 0.0e+00, 3.6e+03],
       [0.0e+00, 0.0e+00, 4.0e+03],
       [0.0e+00, 1.0e+00, 2.6e+03],
       [0.0e+00, 1.0e+00, 2.8e+03],
       [0.0e+00, 1.0e+00, 3.3e+03],
       [0.0e+00, 1.0e+00, 3.6e+03],
       [1.0e+00, 0.0e+00, 2.6e+03],
       [1.0e+00, 0.0e+00, 2.9e+03],
       [1.0e+00, 0.0e+00, 3.1e+03],
       [1.0e+00, 0.0e+00, 3.6e+03]])

In [31]:
model.fit(X,y)

LinearRegression()

In [32]:
model.predict([[1,0,2800]])

array([590775.63964739])

In [33]:
model.predict([[0,1,3400]])

array([681241.6684584])